---

resources:
  - name: git-jira-resource
    type: git
    source:
      uri: git@github.com:((git-username))/jira-resource.git
      branch: master
      private_key: ((private-repo-key))

  - name: jira
    type: jira
    source:
      url: ((jira-url))
      username: ((jira-username))
      password: ((jira-password))
      project: ((jira-project))

resource_types:
- name: jira
  type: docker-image
  source:
    repository: ((git-username))/jira-resource
    tag: latest

jobs:
- name: update-jira
  plan:
  - get: git-jira-resource
    trigger: true
  - put: jira
    params:
      issue_type: ((jira-issuetype))
      summary: Example jira ticket $NOW
      fields:
        description:
          file: git-jira-resource/spec/resources/sample.out
          text: Static text - $FILE
        environment: PROD
        duedate: $NOW+1H
      transitions:
      - ((jira-transition))
  - put: jira
    params:
      parent: ((jira-parent))
      issue_type: ((jira-issuetype))
      summary: Example jira sub ticket from concourse $NOW
      fields:
        description:
          file: git-jira-resource/spec/resources/sample.out
          text: Static text - $FILE
        environment: PROD
        duedate: $NOW+1H
