---

resources:
  - name: git-jira-resource
    type: git
    source:
      uri: git@github.com:((git-username))/jira-resource.git
      branch: master
      private_key: ((private-repo-key))
      ignore_paths: [ package.json ]

  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:((git-username))/jira-resource.git
      branch: version
      private_key: ((private-repo-key))
      file: version

  - name: docker-jira-resource
    type: docker-image
    source:
      repository: ((docker-username))/jira-resource
      username: ((docker-username))
      password: ((docker-password))
      email: ((docker-email))

jobs:
- name: test
  plan:
  - get: git-jira-resource
    trigger: true
  - task: run-tests
    config:
      platform: linux
      image_resource:
        source:
          repository: ((docker-username))/jira-resource
        type: docker-image
      inputs:
      - name: git-jira-resource
      run:
        path: git-jira-resource/ci/scripts/run-tests

- name: build
  plan:
  - get: git-jira-resource
    trigger: true
    passed: [ test ]
  - put: version
    params:
      bump: patch
  - put: docker-jira-resource
    params:
      build: git-jira-resource
      tag: version/version
      tag_as_latest: true

- name: major
  plan:
  - put: version
    params:
      bump: major

- name: minor
  plan:
  - put: version
    params:
      bump: minor
