build:
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
        tests: true
    tests:
        override:
            -
                command: './node_modules/.bin/istanbul cover --report clover --dir reports/coverage src/*.js'
                coverage:
                    file: 'reports/coverage/clover.xml'
                    format: 'clover'
checks:
    javascript: true
