os: linux
dist: focal
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
branches:
  except:
  - version
  
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker --version 
  - docker login --username=ajv21 -p=Jun21@2021
  - docker buildx create --name ajvbuild
  - docker buildx use ajvbuild
  - docker buildx inspect --bootstrap
  - sudo apt-get install qemu qemu-user-static qemu-system-arm
  - docker buildx build -t ajv21/sample:buildx_jira64 --platform linux/amd64,linux/arm64 --push .
  - docker buildx rm ajvbuild
