os: linux
dist: bionic
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
branches:
  except:
  - version
  

script:
  - docker --version 
  - docker login --username=ajv21 -p=Jun21@2021
  - docker buildx create --name vigbuild
  - docker buildx use vigbuild
  - docker buildx inspect --bootstrap
  - free -m
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx build -t ajv21/sample:latest --platform linux/arm64 --push .
  - docker buildx rm vigbuild 
