os: linux
distr:  focal
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
branches:
  except:
  - version
install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version
script:
  - make build
