os: linux
dist: focal
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
branches:
  except:
  - version
  
script:
  - docker --version 
  - docker login --username=ajv21 -p=Jun21@2021
  - docker buildx create --name ajvbuild
  - docker buildx use ajvbuild
  - docker buildx inspect --bootstrap
  - sudo apt-get install qemu qemu-user-static qemu-system-arm
  - docker buildx build -t ajv21/sample:buildx_jira64 --platform linux/amd64,linux/arm64 --push .
  - docker buildx rm ajvbuild
