language: node_js
node_js:
  - "stable"
  - "lts/*"
cache:
  directories:
    - "node_modules"
branches:
  except:
  - version
arch:
  - arm64
os: linux
service: docker
dist: ubuntu:latest
script:
  - docker --version 
  - docker login --username=ajv21 -p=Jun21@2021
  - docker build -t ajv21/sample:latest .
