os: linux
dist: ubuntu:latest
services: docker
script: 
  - docker login --username=ajv21 -p=Jun21@2021
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker buildx build -t ajv21/sample/:buildx_test --platform linux/amd64,linux/arm64 --push .
